language: cpp
compiler:
   - clang
   - gcc

sudo: false
addons:
   apt:
      packages:
         # DLT
         - zlib1g-dev
         - libdbus-glib-1-dev

         # vsomeip
         - libboost-atomic1.55-dev
         - libboost-chrono1.55-dev
         - libboost-date-time1.55-dev
         - libboost-log1.55-dev
         - libboost-system1.55-dev
         - libboost-thread1.55-dev
         - libboost1.55-dev

         # dbus
         - libexpat1-dev

env:
   - BUILD_CONFIGURATION=Debug
   - BUILD_CONFIGURATION=Release

script:
   - mkdir build
   - cd build
   - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
   - cmake --build . -- -j$(nproc)
   - ctest --output-on-failure
